### PR TITLE
Fix standard errors, Replace RichEmbed to object embed, edit gitignore, etc.

### PR DESCRIPTION
**Pull request by Helloyunho**
Object embed might contain many lines, It looks nicer than RichEmbed.

### CODE REVIEW

**Comment by pmh-only** [comment]
It looks fine

**Comment by Helloyunho** [comment]
Please review it and if you liked it please merge it

**Comment by pmh-only** [comment]
@Helloyunho 
We Merged This Commit, but it has bugs

**Comment by Helloyunho** [comment]
Yeah I was going to talk about that but I forgot it sorry

**Pull request merged**
